import { useEffect, useMemo, useState } from 'react';
import { Alert, Dimensions, Image, LayoutAnimation, Modal, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, Switch, Text, TextInput, View } from 'react-native';
import * as Notifications from 'expo-notifications';
import * as DocumentPicker from 'expo-document-picker';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { templates, newExercise, newRoutine, MUSCLE_GROUPS, SET_OPTIONS, REP_OPTIONS, type Exercise, type Routine } from './src/data';
import { defaultState, loadState, saveState, type SavedState } from './src/storage';
import { supabase } from './src/supabase';
import { C } from './src/theme';
import { showWeight } from './src/lib/units';
import { styles } from './src/styles';
import { Workout } from './src/screens/WorkoutScreen';
import { WEEKDAYS, findRoutineById, todayWeekday, type Weekday } from './src/lib/schedule';
import type { WeeklySchedule } from './src/types/schedule';
import { parseScheduleCsv, SAMPLE_CSV } from './src/lib/csvImport';
import { getVolumeBuckets, isRoutineCompletedToday, type VolumeGranularity } from './src/lib/workoutHistory';
import { getPersonalRecords } from './src/lib/prs';
import { getPeriodComparison, percentageChange, type ComparisonGranularity } from './src/lib/weeklyComparison';
import { exerciseNames, exerciseSeries, muscleDistribution, type Metric, type RangeDays } from './src/analytics';
import { LineChart } from './src/charts';
import { StreakCalendar } from './src/components/StreakCalendar';
import './src/lib/layoutAnimation';

type Tab = 'Home' | 'Plans' | 'Progress' | 'Profile';

export default function App() {
  const [state, setState] = useState<SavedState>(defaultState);
  const [ready, setReady] = useState(false); const [tab, setTab] = useState<Tab>('Home');
  const [active, setActive] = useState<Routine | null>(null); const [plansOpen, setPlansOpen] = useState(false);
  const [authOpen, setAuthOpen] = useState(false);
  useEffect(() => { loadState().then(v => { setState(v); setReady(true); }); }, []);
  useEffect(() => { if (ready) saveState(state); }, [state, ready]);
  const update = (patch: Partial<SavedState>) => setState(s => ({ ...s, ...patch }));
  const startRoutine = (r: Routine) => { if (r.exercises.length === 0) { Alert.alert('Add exercises first', "This plan doesn't have any exercises yet. Edit it to add some."); return; } setActive(r); };
  const addRoutine = (r: Routine) => update({ routines: [...state.routines, r] });
  const updateRoutine = (r: Routine) => update({ routines: state.routines.map(x => x.id === r.id ? r : x) });
  const deleteRoutine = (id: string) => update({ routines: state.routines.filter(x => x.id !== id) });
  const assignDay = (day: Weekday, routineId: string | null) => update({ schedule: { ...state.schedule, [day]: routineId ?? undefined } });
  const importSchedule = (newRoutines: Routine[], scheduleAssignments: WeeklySchedule) => update({ routines: [...state.routines, ...newRoutines], schedule: { ...state.schedule, ...scheduleAssignments } });
  if (!ready) return <SafeAreaView style={styles.screen}><Text style={styles.brand}>ZENO<Text style={styles.brandAccent}>FIT</Text></Text></SafeAreaView>;
  if (!state.profile.onboardingDone) return <Onboarding done={(name, unit) => update({ profile: { ...state.profile, name, unit, onboardingDone: true } })} />;
  if (active) return <Workout routine={active} unit={state.profile.unit} history={state.history} finish={(volume, records, history) => { update({ completed: state.completed + 1, volume: state.volume + volume, records: { ...state.records, ...records }, history }); setActive(null); setTab('Progress'); }} cancel={() => setActive(null)} />;
  return <SafeAreaView style={styles.screen}><StatusBar barStyle="light-content" />
    <View style={styles.header}><Text style={styles.brand}>ZENO<Text style={styles.brandAccent}>FIT</Text></Text><Pressable onPress={() => setTab('Profile')}><Text style={styles.avatar}>{state.profile.name.slice(0, 1).toUpperCase() || 'Z'}</Text></Pressable></View>
    {tab === 'Home' && <Home state={state} start={startRoutine} browse={() => setTab('Plans')} />}
    {tab === 'Plans' && <Plans routines={state.routines} schedule={state.schedule} assignDay={assignDay} importSchedule={importSchedule} start={startRoutine} add={addRoutine} updateRoutine={updateRoutine} deleteRoutine={deleteRoutine} />}
    {tab === 'Progress' && <Progress state={state} />}
    {tab === 'Profile' && <Profile state={state} update={update} openAuth={() => setAuthOpen(true)} />}
    <View style={styles.tabs}>{(['Home', 'Plans', 'Progress', 'Profile'] as Tab[]).map(x => <Pressable key={x} style={styles.tab} onPress={() => setTab(x)}><Text style={[styles.tabIcon, tab === x && styles.tabActive]}>{x === 'Home' ? '⌂' : x === 'Plans' ? '▤' : x === 'Progress' ? '↗' : '◉'}</Text><Text style={[styles.tabLabel, tab === x && styles.tabActive]}>{x}</Text></Pressable>)}</View>
    <Auth visible={authOpen} close={() => setAuthOpen(false)} />
  </SafeAreaView>;
}

function Onboarding({ done }: { done: (name: string, unit: 'kg' | 'lb') => void }) { const [name, setName] = useState(''); const [unit, setUnit] = useState<'kg' | 'lb'>('kg'); return <SafeAreaView style={styles.screen}><View style={styles.onboard}><Text style={styles.brand}>ZENO<Text style={styles.brandAccent}>FIT</Text></Text><Text style={styles.hero}>Train with intention.</Text><Text style={styles.sub}>Your routines, lifts, and progress—made simple.</Text><Text style={styles.label}>WHAT SHOULD WE CALL YOU?</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor={C.muted} style={styles.input} /><Text style={styles.label}>PREFERRED UNIT</Text><View style={styles.row}>{(['kg', 'lb'] as const).map(u => <Pressable key={u} onPress={() => setUnit(u)} style={[styles.choice, unit === u && styles.choiceOn]}><Text style={styles.choiceText}>{u.toUpperCase()}</Text></Pressable>)}</View><Pressable style={styles.primary} onPress={() => done(name.trim() || 'Athlete', unit)}><Text style={styles.primaryText}>START TRAINING →</Text></Pressable><Text style={styles.fine}>You can update units and reminders anytime.</Text></View></SafeAreaView> }

function Home({ state, start, browse }: { state: SavedState; start: (r: Routine) => void; browse: () => void }) { const today = todayWeekday(); const scheduled = findRoutineById(state.routines, templates, state.schedule[today]); const suggested = scheduled || state.routines[0] || templates[0]; const doneToday = isRoutineCompletedToday(state.history, suggested.id); return <ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>READY WHEN YOU ARE</Text><Text style={styles.title}>Hey, {state.profile.name}.</Text><View style={styles.feature}><Image source={require('./assets/images/home-hero.jpg')} style={styles.featureImage} /><View style={styles.featureOverlay} /><View style={styles.featureContent}><Text style={styles.featureLabel}>{doneToday ? '✓ COMPLETED TODAY' : scheduled ? `${today.toUpperCase()}’S SESSION` : "TODAY'S SESSION"}</Text><Text style={styles.featureTitle}>{suggested.name}</Text><Text style={styles.sub}>{suggested.exercises.length} exercises · {suggested.duration}</Text><Pressable style={styles.primary} onPress={() => start(suggested)}><Text style={styles.primaryText}>{doneToday ? 'START ANOTHER SESSION' : 'START WORKOUT'}</Text></Pressable></View></View><Text style={styles.section}>Your week</Text><View style={styles.stats}><Stat value={String(state.completed)} label="Workouts" /><Stat value={`${Math.round(state.volume / 1000 * 10) / 10}k`} label="Volume (kg)" /><Stat value={String(Object.keys(state.records).length)} label="Records" /></View><Pressable style={styles.secondary} onPress={browse}><Text style={styles.secondaryText}>Browse workout plans</Text><Text style={styles.secondaryText}>→</Text></Pressable></ScrollView> }
function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View> }

function Plans({ routines, schedule, assignDay, importSchedule, start, add, updateRoutine, deleteRoutine }: { routines: Routine[]; schedule: WeeklySchedule; assignDay: (day: Weekday, routineId: string | null) => void; importSchedule: (routines: Routine[], schedule: WeeklySchedule) => void; start: (r: Routine) => void; add: (r: Routine) => void; updateRoutine: (r: Routine) => void; deleteRoutine: (id: string) => void }) {
  const [editorVisible, setEditorVisible] = useState(false);
  const [editing, setEditing] = useState<Routine | null>(null);
  const openNew = () => { setEditing(null); setEditorVisible(true); };
  const openEdit = (r: Routine) => { setEditing(r); setEditorVisible(true); };
  const onSave = (r: Routine) => { if (editing) updateRoutine(r); else add(r); };
  const duplicateTemplate = (t: Routine) => add({ ...t, id: `custom-${Date.now()}`, name: `${t.name} (copy)`, template: false });
  const confirmDelete = (r: Routine) => Alert.alert('Delete plan?', `"${r.name}" will be removed permanently.`, [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: () => deleteRoutine(r.id) }]);
  return <ScrollView contentContainerStyle={styles.content}>
    <View style={styles.titleRow}><View><Text style={styles.eyebrow}>YOUR TRAINING</Text><Text style={styles.title}>Workout plans</Text></View><Pressable style={styles.add} onPress={openNew}><Text style={styles.addText}>＋</Text></Pressable></View>
    <WeeklySchedule routines={routines} schedule={schedule} assignDay={assignDay} importSchedule={importSchedule} />
    {routines.length > 0 && <Text style={styles.section}>MY PLANS</Text>}
    {routines.map(r => <View style={styles.routine} key={r.id}><View style={styles.routineTop}><View><Text style={styles.routineName}>{r.name}</Text><Text style={styles.sub}>{r.focus}</Text></View><Text style={styles.duration}>{r.duration}</Text></View><Text style={styles.exercisePreview}>{r.exercises.length ? r.exercises.map(e => e.name).join(' · ') : 'No exercises yet — tap Edit to add some'}</Text><View style={styles.row}><Pressable style={[styles.secondary, styles.flex1]} onPress={() => start(r)}><Text style={styles.secondaryText}>Start</Text></Pressable><Pressable style={[styles.secondary, styles.flex1]} onPress={() => openEdit(r)}><Text style={styles.secondaryText}>Edit</Text></Pressable><Pressable style={[styles.secondary, styles.flex1]} onPress={() => confirmDelete(r)}><Text style={[styles.secondaryText, styles.dangerText]}>Delete</Text></Pressable></View></View>)}
    <Text style={styles.section}>TEMPLATES</Text>
    {templates.map(t => <View style={styles.routine} key={t.id}><View style={styles.routineTop}><View><Text style={styles.routineName}>{t.name}</Text><Text style={styles.sub}>{t.focus}</Text></View><Text style={styles.duration}>{t.duration}</Text></View><Text style={styles.exercisePreview}>{t.exercises.map(e => e.name).join(' · ')}</Text><View style={styles.row}><Pressable style={[styles.secondary, styles.flex1]} onPress={() => start(t)}><Text style={styles.secondaryText}>Start</Text></Pressable><Pressable style={[styles.secondary, styles.flex1]} onPress={() => duplicateTemplate(t)}><Text style={styles.secondaryText}>Customize</Text></Pressable></View></View>)}
    <PlanEditor visible={editorVisible} initial={editing} close={() => setEditorVisible(false)} save={onSave} />
  </ScrollView>;
}

function WeeklySchedule({ routines, schedule, assignDay, importSchedule }: { routines: Routine[]; schedule: WeeklySchedule; assignDay: (day: Weekday, routineId: string | null) => void; importSchedule: (routines: Routine[], schedule: WeeklySchedule) => void }) {
  const [expandedDay, setExpandedDay] = useState<Weekday | null>(null); const today = todayWeekday(); const options = [...routines, ...templates];
  const toggleDay = (day: Weekday) => { LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut); setExpandedDay(d => d === day ? null : day); };
  const selectDayPlan = (day: Weekday, routineId: string | null) => { assignDay(day, routineId); LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut); setExpandedDay(null); };
  const importFromCsv = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: '*/*', copyToCacheDirectory: true }); if (result.canceled || !result.assets[0]) return; const asset = result.assets[0]; const text = asset.file ? await asset.file.text() : await new File(asset.uri).text(); const parsed = parseScheduleCsv(text); const dayCount = Object.keys(parsed.schedule).length; Alert.alert('Import schedule?', `This will add ${parsed.routines.length} plan${parsed.routines.length === 1 ? '' : 's'} and assign ${dayCount} day${dayCount === 1 ? '' : 's'} of your week.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Import', onPress: () => importSchedule(parsed.routines, parsed.schedule) }]); } catch (err) { Alert.alert('Import failed', err instanceof Error ? err.message : 'Could not read that CSV file.'); } };
  const downloadSampleCsv = async () => { try { if (Platform.OS === 'web') { const blob = new Blob([SAMPLE_CSV], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'schedule-sample.csv'; document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url); return; } const file = new File(Paths.cache, 'schedule-sample.csv'); if (file.exists) file.delete(); file.create(); file.write(SAMPLE_CSV); if (!(await Sharing.isAvailableAsync())) { Alert.alert('Sharing unavailable', 'Your device does not support sharing files.'); return; } await Sharing.shareAsync(file.uri, { mimeType: 'text/csv', dialogTitle: 'Save sample schedule CSV' }); } catch (err) { Alert.alert('Could not create sample file', err instanceof Error ? err.message : 'Please try again.'); } };
  return <><View style={styles.titleRow}><Text style={styles.section}>WEEKLY SCHEDULE</Text><View style={styles.row}><Pressable onPress={downloadSampleCsv}><Text style={styles.link}>Sample CSV</Text></Pressable><Pressable onPress={importFromCsv}><Text style={styles.link}>Import CSV</Text></Pressable></View></View><View style={styles.scheduleRow}>{WEEKDAYS.map(day => { const routine = findRoutineById(routines, templates, schedule[day]); return <Pressable key={day} style={[styles.scheduleDay, day === today && styles.scheduleDayToday, expandedDay === day && styles.scheduleDayExpanded]} onPress={() => toggleDay(day)}><Text style={styles.scheduleDayLabel}>{day.slice(0, 3).toUpperCase()}</Text>{routine ? <Text style={styles.scheduleDayRoutine} numberOfLines={2}>{routine.name}</Text> : <Text style={styles.scheduleDayRest}>Rest</Text>}</Pressable>; })}</View>{expandedDay && <View style={styles.scheduleOptions}><Text style={styles.modalTitle}>{expandedDay}</Text><Pressable style={styles.secondary} onPress={() => selectDayPlan(expandedDay, null)}><Text style={styles.secondaryText}>Rest day</Text></Pressable>{options.map(r => <Pressable key={r.id} style={styles.secondary} onPress={() => selectDayPlan(expandedDay, r.id)}><Text style={styles.secondaryText}>{r.name}</Text></Pressable>)}</View>}</>;
}

function PlanEditor({ visible, initial, close, save }: { visible: boolean; initial: Routine | null; close: () => void; save: (r: Routine) => void }) {
  const [name, setName] = useState(''); const [focus, setFocus] = useState(''); const [duration, setDuration] = useState('45 min'); const [exercises, setExercises] = useState<Exercise[]>([]);
  useEffect(() => { if (!visible) return; const base = initial ?? newRoutine(); setName(initial ? base.name : ''); setFocus(base.focus); setDuration(base.duration); setExercises(base.exercises); }, [visible, initial]);
  const addEx = () => setExercises(ex => [...ex, newExercise()]); const updateEx = (id: string, patch: Partial<Exercise>) => setExercises(ex => ex.map(e => e.id === id ? { ...e, ...patch } : e)); const removeEx = (index: number) => setExercises(ex => ex.filter((_, currentIndex) => currentIndex !== index));
  const moveEx = (id: string, dir: -1 | 1) => setExercises(ex => { const i = ex.findIndex(e => e.id === id); const j = i + dir; if (j < 0 || j >= ex.length) return ex; const copy = [...ex]; [copy[i], copy[j]] = [copy[j], copy[i]]; return copy; });
  const canSave = name.trim().length > 0 && exercises.length > 0 && exercises.every(e => e.name.trim().length > 0);
  const onSave = () => { save({ id: initial?.id ?? newRoutine().id, name: name.trim(), focus: focus.trim() || 'Custom plan', duration: duration.trim() || '45 min', exercises, template: false }); close(); };
  return <Modal visible={visible} animationType="slide" onRequestClose={close}><SafeAreaView style={styles.screen}><View style={styles.workHeader}><Pressable hitSlop={16} onPress={close}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.workTitle}>{initial ? 'Edit plan' : 'New plan'}</Text><Pressable onPress={onSave} disabled={!canSave}><Text style={[styles.secondaryText, styles.saveText, !canSave && styles.saveTextDisabled]}>SAVE</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.label}>PLAN NAME</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Leg Day" placeholderTextColor={C.muted} style={styles.input} /><Text style={styles.label}>FOCUS</Text><TextInput value={focus} onChangeText={setFocus} placeholder="e.g. Strength · Lower body" placeholderTextColor={C.muted} style={styles.input} /><Text style={styles.label}>DURATION</Text><TextInput value={duration} onChangeText={setDuration} placeholder="e.g. 45 min" placeholderTextColor={C.muted} style={styles.input} /><View style={styles.titleRow}><Text style={styles.section}>Exercises</Text><Pressable style={styles.add} onPress={addEx}><Text style={styles.addText}>＋</Text></Pressable></View>{exercises.length === 0 && <View style={styles.empty}><Text style={styles.emptyIcon}>＋</Text><Text style={styles.routineName}>No exercises yet</Text><Text style={styles.sub}>Tap the + button to add your first exercise.</Text></View>}{exercises.map((e, i) => <ExerciseRow key={e.id} exercise={e} onChange={patch => updateEx(e.id, patch)} onRemove={() => Alert.alert('Remove exercise?', `Remove ${e.name || 'this exercise'} from this plan?`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => removeEx(i) }])} onMove={dir => moveEx(e.id, dir)} isFirst={i === 0} isLast={i === exercises.length - 1} />)}</ScrollView></SafeAreaView></Modal>;
}

function ExerciseRow({ exercise, onChange, onRemove, onMove, isFirst, isLast }: { exercise: Exercise; onChange: (patch: Partial<Exercise>) => void; onRemove: () => void; onMove: (dir: -1 | 1) => void; isFirst: boolean; isLast: boolean }) { return <View style={styles.exerciseEdit}><View style={styles.exerciseEditTop}><TextInput value={exercise.name} onChangeText={name => onChange({ name })} placeholder="Exercise name" placeholderTextColor={C.muted} style={[styles.input, styles.flex1]} /><Pressable onPress={onRemove} style={styles.removeBtn} accessibilityRole="button" accessibilityLabel={`Remove ${exercise.name || 'exercise'}`} hitSlop={10}><Text style={styles.removeBtnText}>REMOVE</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.muscleChips}>{MUSCLE_GROUPS.map(m => <Pressable key={m} onPress={() => onChange({ muscle: m })} style={[styles.muscleChip, exercise.muscle === m && styles.muscleChipOn]}><Text style={[styles.muscleChipText, exercise.muscle === m && styles.muscleChipTextOn]}>{m}</Text></Pressable>)}</ScrollView><Text style={styles.miniLabel}>SETS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.muscleChips}>{SET_OPTIONS.map(n => <Pressable key={n} onPress={() => onChange({ sets: n })} style={[styles.muscleChip, exercise.sets === n && styles.muscleChipOn]}><Text style={[styles.muscleChipText, exercise.sets === n && styles.muscleChipTextOn]}>{n}</Text></Pressable>)}</ScrollView><Text style={styles.miniLabel}>REPS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.muscleChips}>{REP_OPTIONS.map(r => <Pressable key={r} onPress={() => onChange({ reps: r })} style={[styles.muscleChip, exercise.reps === r && styles.muscleChipOn]}><Text style={[styles.muscleChipText, exercise.reps === r && styles.muscleChipTextOn]}>{r}</Text></Pressable>)}</ScrollView><View style={styles.moveRow}><Pressable disabled={isFirst} onPress={() => onMove(-1)} style={[styles.moveBtn, isFirst && styles.moveBtnDisabled]}><Text style={styles.moveBtnText}>↑ Move up</Text></Pressable><Pressable disabled={isLast} onPress={() => onMove(1)} style={[styles.moveBtn, isLast && styles.moveBtnDisabled]}><Text style={styles.moveBtnText}>↓ Move down</Text></Pressable></View></View>; }

function Progress({ state }: { state: SavedState }) {
  const entries = Object.entries(state.records);
  const prs = useMemo(() => getPersonalRecords(state.history), [state.history]);
  const [volumeGranularity, setVolumeGranularity] = useState<VolumeGranularity>('day');
  const volumeCount = volumeGranularity === 'day' ? 7 : volumeGranularity === 'week' ? 8 : 6;
  const buckets = useMemo(() => getVolumeBuckets(state.history, volumeGranularity, volumeCount), [state.history, volumeGranularity, volumeCount]);
  const hasTrend = buckets.some(b => b.value > 0); const maxVolume = Math.max(...buckets.map(b => b.value), 1);
  const names = useMemo(() => exerciseNames(state.history), [state.history]); const [exercise, setExercise] = useState<string | null>(null); const [metric, setMetric] = useState<Metric>('weight'); const [range, setRange] = useState<RangeDays>(90); const activeExercise = exercise && names.includes(exercise) ? exercise : names[0] ?? null; const chartWidth = Dimensions.get('window').width - 20 * 2 - 18 * 2;
  const series = useMemo(() => activeExercise ? exerciseSeries(state.history, activeExercise, metric, range) : [], [state.history, activeExercise, metric, range]);
  const points = series.map(p => ({ x: p.date, y: metric === 'weight' || metric === '1rm' ? (state.profile.unit === 'kg' ? p.value : p.value * 2.20462) : p.value, label: new Date(p.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }));
  const metricUnit = metric === 'weight' || metric === '1rm' ? state.profile.unit : metric === 'volume' ? `${state.profile.unit}·reps` : 'reps';
  const [muscleRange, setMuscleRange] = useState<RangeDays>(30); const muscleVolumes = useMemo(() => muscleDistribution(state.history, muscleRange), [state.history, muscleRange]); const muscleTotal = muscleVolumes.reduce((sum, m) => sum + m.volume, 0) || 1;
  const [comparisonGranularity, setComparisonGranularity] = useState<ComparisonGranularity>('week');
  const comparison = useMemo(() => getPeriodComparison(state.history, comparisonGranularity), [state.history, comparisonGranularity]);
  const changeColor = (pct: number | null) => pct === null || pct === 0 ? C.muted : pct > 0 ? C.lime : C.danger;
  const changeLabel = (pct: number | null) => pct === null ? 'new' : `${pct > 0 ? '+' : ''}${pct.toFixed(0)}%`;
  return <ScrollView contentContainerStyle={styles.content}>
    <Text style={styles.eyebrow}>YOUR RESULTS</Text><Text style={styles.title}>Progress</Text>
    <View style={styles.stats}><Stat value={String(state.completed)} label="Sessions" /><Stat value={`${Math.round(state.volume).toLocaleString()}`} label="Volume (kg)" /><Stat value={String(prs.length)} label="PRs" /></View>
    <Text style={styles.section}>Personal records</Text>
    {entries.length ? entries.map(([name, kg]) => <View style={styles.record} key={name}><View><Text style={styles.routineName}>{name}</Text><Text style={styles.sub}>Best lifted weight</Text></View><Text style={styles.recordValue}>{showWeight(kg, state.profile.unit)}</Text></View>) : <View style={styles.empty}><Text style={styles.emptyIcon}>↗</Text><Text style={styles.routineName}>Your progress starts here</Text><Text style={styles.sub}>Complete a workout to see your strength trends and personal records.</Text></View>}
    <Text style={styles.section}>Recent PRs</Text>
    {prs.length ? prs.slice(0, 12).map((pr, index) => <View style={styles.record} key={`${pr.exercise}-${pr.type}-${pr.date}-${index}`}><View style={styles.flex1}><Text style={styles.routineName}>{pr.exercise}</Text><Text style={styles.sub}>{pr.type === 'weight' ? 'Weight PR' : 'Estimated 1RM PR'} · {new Date(pr.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</Text></View><Text style={styles.recordValue}>{showWeight(pr.value, state.profile.unit)}{pr.type === '1rm' ? ' 1RM' : ''}</Text></View>) : <View style={styles.empty}><Text style={styles.emptyIcon}>★</Text><Text style={styles.routineName}>No PRs yet</Text><Text style={styles.sub}>Your first set establishes a baseline. Beat it in a later workout to log a PR.</Text></View>}

    <Text style={styles.section}>This {comparisonGranularity} vs last</Text>
    <View style={styles.chart}>
      <View style={styles.segmented}>{(['week', 'month'] as ComparisonGranularity[]).map(g => <Pressable key={g} onPress={() => setComparisonGranularity(g)} style={[styles.segment, comparisonGranularity === g && styles.segmentOn]}><Text style={[styles.segmentText, comparisonGranularity === g && styles.segmentTextOn]}>{g === 'week' ? 'Week' : 'Month'}</Text></Pressable>)}</View>
      {([
        { label: 'Sessions', current: comparison.current.sessions, previous: comparison.previous.sessions, format: (n: number) => String(n) },
        { label: 'Volume', current: comparison.current.volume, previous: comparison.previous.volume, format: (n: number) => Math.round(n).toLocaleString() },
        { label: 'Sets', current: comparison.current.sets, previous: comparison.previous.sets, format: (n: number) => String(n) },
        { label: 'PRs hit', current: comparison.current.prs, previous: comparison.previous.prs, format: (n: number) => String(n) },
      ]).map(row => { const pct = percentageChange(row.current, row.previous); return <View style={styles.record} key={row.label}>
        <View><Text style={styles.routineName}>{row.label}</Text><Text style={styles.sub}>{row.format(row.previous)} last {comparisonGranularity}</Text></View>
        <View style={styles.comparisonAlign}><Text style={styles.recordValue}>{row.format(row.current)}</Text><Text style={[styles.miniLabel, { color: changeColor(pct) }]}>{changeLabel(pct)}</Text></View>
      </View>; })}
    </View>
    <Text style={styles.section}>Workout streak</Text>
    <StreakCalendar history={state.history} />
    <Text style={styles.section}>Training volume</Text>
    <View style={styles.chart}><View style={styles.segmented}>{(['day', 'week', 'month'] as VolumeGranularity[]).map(g => <Pressable key={g} onPress={() => setVolumeGranularity(g)} style={[styles.segment, volumeGranularity === g && styles.segmentOn]}><Text style={[styles.segmentText, volumeGranularity === g && styles.segmentTextOn]}>{g === 'day' ? 'Daily' : g === 'week' ? 'Weekly' : 'Monthly'}</Text></Pressable>)}</View><Text style={styles.sub}>{hasTrend ? `Total volume lifted, last ${volumeCount} ${volumeGranularity === 'day' ? 'days' : volumeGranularity === 'week' ? 'weeks' : 'months'}.` : 'Charts will build from completed workout history.'}</Text><View style={styles.chartLine}>{buckets.map((b, i) => <View key={i} style={[styles.bar, { height: hasTrend ? Math.max(4, (b.value / maxVolume) * 78) : 4 }]} />)}</View><View style={styles.barLabels}>{buckets.map((b, i) => <Text key={i} style={styles.miniLabel}>{b.label}</Text>)}</View></View>
    <Text style={styles.section}>Exercise trends</Text>
    {names.length === 0 ? <View style={styles.empty}><Text style={styles.emptyIcon}>↗</Text><Text style={styles.routineName}>No exercise history yet</Text><Text style={styles.sub}>Log a couple of workouts and this section will chart your trend per exercise.</Text></View> : <><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.muscleChips}>{names.map(n => <Pressable key={n} onPress={() => setExercise(n)} style={[styles.muscleChip, activeExercise === n && styles.muscleChipOn]}><Text style={[styles.muscleChipText, activeExercise === n && styles.muscleChipTextOn]}>{n}</Text></Pressable>)}</ScrollView><View style={styles.chart}><View style={styles.row}><View style={styles.segmented}>{(['weight', 'reps', 'volume', '1rm'] as Metric[]).map(m => <Pressable key={m} onPress={() => setMetric(m)} style={[styles.segment, metric === m && styles.segmentOn]}><Text style={[styles.segmentText, metric === m && styles.segmentTextOn]}>{m === 'weight' ? 'Weight' : m === 'reps' ? 'Reps' : m === 'volume' ? 'Volume' : '1RM'}</Text></Pressable>)}</View></View><View style={styles.row}><View style={styles.segmented}>{([30, 90, 0] as RangeDays[]).map(r => <Pressable key={r} onPress={() => setRange(r)} style={[styles.segment, range === r && styles.segmentOn]}><Text style={[styles.segmentText, range === r && styles.segmentTextOn]}>{r === 0 ? 'All' : `${r}d`}</Text></Pressable>)}</View></View><LineChart points={points} width={chartWidth} height={140} color={C.lime} gridColor={C.panel2} mutedColor={C.muted} formatY={v => `${v.toFixed(0)} ${metricUnit}`} emptyLabel="No sessions in this range" />{metric === '1rm' && <Text style={styles.miniLabel}>Estimated via Epley formula: weight × (1 + reps ÷ 30). Not a substitute for an actual tested max.</Text>}</View></>}
    <Text style={styles.section}>Muscle balance</Text>
    {muscleVolumes.length === 0 ? <View style={styles.empty}><Text style={styles.emptyIcon}>↗</Text><Text style={styles.routineName}>No sets logged yet</Text><Text style={styles.sub}>Complete a workout and this section will show which muscle groups you're training most.</Text></View> : <View style={styles.chart}><View style={styles.segmented}>{([30, 90, 0] as RangeDays[]).map(r => <Pressable key={r} onPress={() => setMuscleRange(r)} style={[styles.segment, muscleRange === r && styles.segmentOn]}><Text style={[styles.segmentText, muscleRange === r && styles.segmentTextOn]}>{r === 0 ? 'All' : `${r}d`}</Text></Pressable>)}</View>{muscleVolumes.map(m => <View style={styles.muscleRow} key={m.muscle}><Text style={styles.muscleRowLabel}>{m.muscle}</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${Math.round((m.volume / muscleTotal) * 100)}%` }]} /></View><Text style={styles.muscleRowValue}>{Math.round(m.volume).toLocaleString()}</Text></View>)}</View>}
  </ScrollView>;
}

function Profile({ state, update, openAuth }: { state: SavedState; update: (p: Partial<SavedState>) => void; openAuth: () => void }) { const profile = state.profile; const toggleReminder = async (on: boolean) => { if (on) { await Notifications.requestPermissionsAsync(); await Notifications.cancelAllScheduledNotificationsAsync(); await Notifications.scheduleNotificationAsync({ content: { title: 'Time to train', body: 'Your next workout is waiting.' }, trigger: { type: Notifications.SchedulableTriggerInputTypes.DAILY, hour: 18, minute: 0 } as Notifications.NotificationTriggerInput }); } else await Notifications.cancelAllScheduledNotificationsAsync(); update({ profile: { ...profile, reminder: on } }); }; return <ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ACCOUNT</Text><Text style={styles.title}>{profile.name}</Text><Text style={styles.section}>Preferences</Text><View style={styles.setting}><View><Text style={styles.routineName}>Weight unit</Text><Text style={styles.sub}>Display weights in your preferred unit</Text></View><View style={styles.unitToggle}>{(['kg', 'lb'] as const).map(u => <Pressable key={u} onPress={() => update({ profile: { ...profile, unit: u } })}><Text style={[styles.unit, profile.unit === u && styles.unitOn]}>{u.toUpperCase()}</Text></Pressable>)}</View></View><View style={styles.setting}><View><Text style={styles.routineName}>Workout reminder</Text><Text style={styles.sub}>Daily at 6:00 PM</Text></View><Switch value={profile.reminder} onValueChange={toggleReminder} trackColor={{ true: C.lime }} /></View><Text style={styles.section}>Cloud sync</Text><View style={styles.sync}><Text style={styles.sub}>{supabase ? 'Sign in to secure your training history.' : 'Demo mode — add Supabase keys to enable cloud sync.'}</Text><Pressable style={styles.secondary} onPress={openAuth}><Text style={styles.secondaryText}>{supabase ? 'Sign in or create account' : 'View connection setup'}</Text><Text style={styles.secondaryText}>→</Text></Pressable></View></ScrollView> }
function Auth({ visible, close }: { visible: boolean; close: () => void }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const submit = async (signup: boolean) => { if (!supabase) return Alert.alert('Cloud sync setup', 'Copy .env.example to .env and add your Supabase project URL and anonymous key. Then restart Expo.'); setBusy(true); const res = signup ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (res.error) Alert.alert('Could not continue', res.error.message); else { Alert.alert(signup ? 'Check your inbox' : 'Signed in', signup ? 'Confirm your email to finish setting up your account.' : 'Your cloud session is active.'); close(); } }; return <Modal visible={visible} transparent animationType="slide"><View style={styles.modalShade}><View style={styles.modal}><Text style={styles.modalTitle}>Cloud sync</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor={C.muted} style={styles.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password (6+ characters)" placeholderTextColor={C.muted} style={styles.input}/><Pressable style={styles.primary} onPress={() => submit(false)} disabled={busy}><Text style={styles.primaryText}>SIGN IN</Text></Pressable><Pressable onPress={() => submit(true)}><Text style={styles.link}>Create an account</Text></Pressable><Pressable onPress={close}><Text style={styles.cancelText}>Close</Text></Pressable></View></View></Modal> }
