create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, unit text not null default 'kg' check (unit in ('kg','lb')), training_days int[] default '{}', created_at timestamptz default now());
create table public.routines (id uuid primary key default gen_random_uuid(), owner_id uuid references auth.users(id) on delete cascade, name text not null, focus text, is_template boolean not null default false, created_at timestamptz default now());
create table public.routine_exercises (id uuid primary key default gen_random_uuid(), routine_id uuid not null references public.routines(id) on delete cascade, exercise_name text not null, muscle_group text, position int not null, target_sets int not null default 3, target_reps text);
create table public.workouts (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, routine_id uuid references public.routines(id) on delete set null, started_at timestamptz not null default now(), completed_at timestamptz, notes text);
create table public.workout_sets (id uuid primary key default gen_random_uuid(), workout_id uuid not null references public.workouts(id) on delete cascade, exercise_name text not null, set_number int not null, weight_kg numeric not null default 0, reps int not null, rpe numeric, notes text, completed boolean not null default true);
alter table public.profiles enable row level security; alter table public.routines enable row level security; alter table public.routine_exercises enable row level security; alter table public.workouts enable row level security; alter table public.workout_sets enable row level security;
create policy "own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "own or templates routines" on public.routines for select using (owner_id = auth.uid() or is_template); create policy "own routines write" on public.routines for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "routine exercise read" on public.routine_exercises for select using (exists (select 1 from public.routines r where r.id = routine_id and (r.owner_id = auth.uid() or r.is_template)));
create policy "routine exercise write" on public.routine_exercises for all using (exists (select 1 from public.routines r where r.id = routine_id and r.owner_id = auth.uid())) with check (exists (select 1 from public.routines r where r.id = routine_id and r.owner_id = auth.uid()));
create policy "own workouts" on public.workouts for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "own workout sets" on public.workout_sets for all using (exists (select 1 from public.workouts w where w.id = workout_id and w.owner_id = auth.uid())) with check (exists (select 1 from public.workouts w where w.id = workout_id and w.owner_id = auth.uid()));

